apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  labels:
    app: postgres
type: Opaque
stringData:
  password: postgres
  database_uri: postgresql+psycopg://postgres:postgres@postgres-service:5432/promotions
